using System;
using System.Text;
using System.Collections.Generic;
using System.Linq;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using BeSharp.NumberVerification;
using BeSharp.Generic;

namespace NumberVerificationTestProject
{
    /// <summary>
    /// http://nl.wikipedia.org/wiki/Elfproef / http://en.wikipedia.org/wiki/Check_digit
    /// </summary>
    [TestClass]
    public class BankrekeningNummerVerificationUnitTest
    {
        readonly string[] invalidBankrekeningNummerTestNummers = 
        { 
            "5780076210", "8888950501", "2570126352", "6822313203", "4490777794", "4669658485", "6769091146", "5118605967", "1609038688", "7174960489", 
            "242993380", "838606001", "917005932", "918089953", "304195544", "284151115", "880107076", "140206447", "144116568", "705366179", 
            "959446150" // "959446150" generated by Testnummers.nl
        };
        readonly string[] validBankrekeningNummerTestNummers = 
        { 
            "5780076219", "8888950508", "2570126357", "6822313206", "4490777795", "4669658484", "6769091143", "5118605962", "1609038681", "7174960480", 
            "242993389", "838606008", "917005937", "918089956", "304195545", "284151114", "880107073", "140206442", "144116561", "705366170" 
        }; 

        readonly string[] becomesTenDigits = { "000000000", "000000001", "000000002", "000000003", "000000004", "000000005", "000000007", "000000008", "000000009" }; //"123456789";
        readonly string[] cannotBecomeTenDigits = { "000000006", "095944615" }; //"123456789";

        [TestMethod]
        public void Generate_TestMethod()
        {
            for (int i = 0; i < 1000; i++)
            {
                for (int length = BankrekeningNummerVerification.MinBankRekeningNummerLength; length < BankrekeningNummerVerification.MaxBankRekeningNummerLength; length++)
                {
                    string generatedBankrekeningNummer = BankrekeningNummerVerification.Generate(length);
                    bool validBankrekeningNummer = BankrekeningNummerVerification.IsValid(generatedBankrekeningNummer);
                    Assert.IsTrue(validBankrekeningNummer, "Generated {0} is invalid", Reflector.GetNameSeparatorValue(new { generatedBankrekeningNummer }));                    
                }
            }
        }

        [TestMethod]
        public void IsValid_TestMethod()
        {
            foreach (string inValidBankrekeningNummerTestNummer in invalidBankrekeningNummerTestNummers)
            {
                bool result = BankrekeningNummerVerification.IsValid(inValidBankrekeningNummerTestNummer);
                bool expected = false;
                Assert.AreEqual(expected, result, "Expected BankrekeningNummerVerification.IsValid({0} to be {1}", inValidBankrekeningNummerTestNummer, expected);
            }

            foreach (string validBankrekeningNummerTestNummer in validBankrekeningNummerTestNummers)
            {
                bool result = BankrekeningNummerVerification.IsValid(validBankrekeningNummerTestNummer);
                bool expected = true;
                Assert.AreEqual(expected, result, "Expected BankrekeningNummerVerification.IsValid({0} to be {1}", validBankrekeningNummerTestNummer, expected);
            }
        }

        [TestMethod]
        [ExpectedException(typeof(Exception<BankrekeningNummerVerification>))]
        public void Complete_TestMethod()
        {
            foreach (string becomesTenDigit in becomesTenDigits)
            {
                string tenDigit = BankrekeningNummerVerification.Complete(becomesTenDigit);
                bool valid = BankrekeningNummerVerification.IsValid(tenDigit);
                Assert.IsTrue(valid, "Completed {0} into {1}, but {1} was not valid", becomesTenDigit, tenDigit);
            }

            Exception exception = null;
            foreach (string cannotBecomeTenDigit in cannotBecomeTenDigits)
            {
                try
                {
                    string tenDigit = BankrekeningNummerVerification.Complete(cannotBecomeTenDigit);
                    Assert.Inconclusive("It should not be possible that {0} completed into {1}", Reflector.GetNameSeparatorValue(new { cannotBecomeTenDigit }), Reflector.GetNameSeparatorValue(new { tenDigit }));
                }
                catch (Exception ex)
                {
                    exception = ex;
                    continue;
                }
            }
            throw exception;
        }
    }
}
